# Generated by Django 6.0.6 on 2026-06-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_flat_has_balcony'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, choices=[(None, 'Неизвестно'), (True, 'Да'), (False, 'Нет')], db_index=True, null=True, verbose_name='Новостройка'),
        ),
    ]
