# Generated by Django 6.0.6 on 2026-06-27 08:44

from phonenumbers import (format_number, is_valid_number, NumberParseException,
                          parse, PhoneNumberFormat)
from django.db import migrations


def normalize_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    updates = []

    for flat in Flat.objects.all().only('id', 'owners_phonenumber',
                                        'owner_pure_phone').iterator(chunk_size=1000):
        try:
            str_number = flat.owners_phonenumber.strip()
            if str_number and str_number[0] == '8':
                str_number = '+7' + str_number[1:]

            parsed_number = parse(str_number, 'RU')
            if is_valid_number(parsed_number):
                flat.owner_pure_phone = format_number(parsed_number, PhoneNumberFormat.E164)
            else:
                flat.owner_pure_phone = ''

            updates.append(flat)

            if len(updates) >= 1000:
                Flat.objects.bulk_update(updates, ['owner_pure_phone'])
                updates.clear()
        except NumberParseException:
            continue

    if updates:
        Flat.objects.bulk_update(updates, ['owner_pure_phone'])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phonenumbers),
    ]
