# Generated by Django 6.0.6 on 2026-06-27 12:08

from django.db import migrations


def migrate_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all().only('id', 'owner', 'owners_phonenumber',
                                        'owner_pure_phone').iterator(chunk_size=1000):
        owner, created = Owner.objects.get_or_create(full_name=flat.owner,
                                                     phonenumber=flat.owners_phonenumber,
                                                     pure_phone=flat.owner_pure_phone)
        owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(migrate_owners),
    ]
